# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53fe39141a1dfaeb8046faf6bfc0a0aa61f68d4799159d1bcb6799d916c85e9cb821d4435186801b09e42770b90509a804ec5b203af1dd99c1d4b4697baaba02

test:
  secret_key_base: aff97d08c49e17d22c79e5b1ac58383c3c2c02a40407ad9f4b867e140a2885b0819485432b63d7ccda1f3c94f2e8d497cfbb0d9463a45cda4b60dc978bfad5a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
